### ISSUE TITLE
BadSignature('Signature is not valid')

### ISSUE THREAD

**Issue by Romko775** [georgemarshall/django-cryptography#44]
After installation & adding to model raises next error 

Traceback (most recent call last):
  File "XXX/env/lib/python3.7/site-packages/django_cryptography/core/signing.py", line 223, in unsign
    version, timestamp, value, sig = struct.unpack(fmt, signed_value)
struct.error: bad char in struct format

During handling of the above exception, another exception occurred:

XXX/env/lib/python3.7/site-packages/django_cryptography/core/signing.py", line 225, in unsign
    raise BadSignature('Signature is not valid')

**Comment by thismatters** [comment]
what version of the library are you using?

**Comment by Gilwyad** [comment]
I am getting the same error with:

- django-cryptography==1.0
- cryptography==3.0
- Django==3.0.8
- djangorestframework==3.11.0


```
Traceback (most recent call last):
  File ".venv/lib/python3.8/site-packages/django_cryptography/core/signing.py", line 223, in unsign
    version, timestamp, value, sig = struct.unpack(fmt, signed_value)
struct.error: bad char in struct format
```

```
  File ".venv/lib/python3.8/site-packages/django_cryptography/core/signing.py", line 225, in unsign
    raise BadSignature('Signature is not valid')
django.core.signing.BadSignature: Signature is not valid
```

**Comment by ademidun** [comment]
>  After I deleted them and created new encrypted values, I no longer get this error!

How do I do this please?

I've followed along all the different tutorials and I'm still stuck, this is happening in my production datasbe so I can't just delete all data and start from scratch. Please help, my entire website is not loading because of this.

**Comment by ademidun** [comment]
>  After I deleted them and created new encrypted values, I no longer get this error!

How do I do this please? @Gilwyad @thismatters 

This is happening in my production database so I can't just delete all data and start from scratch

 Please help, a significant part of my API is non-responsive because of this error.

I've followed along all the different tutorials and I'm still stuck:

- https://django-cryptography.readthedocs.io/en/latest/migrating.html
- https://github.com/georgemarshall/django-cryptography/issues/11#issuecomment-419720581

- https://github.com/georgemarshall/django-cryptography/issues/45#issuecomment-726843961
- https://gist.github.com/thismatters/53787f2d021fa5a1df640cd7b98d1185

**Comment by thismatters** [comment]
When I experienced this I think the root cause was the python container that I was running in changed the way certain dependencies in the cryptography toolchain were presenting. I fixed the issue by upgrading my application to a more recent python release container (3.8). 

Best of luck to you in troubleshooting this issue. Be aware that dependency changes up and down your stack can cause this issue. It likely __does not__ mean that your data has been lost, but just that something changed.

**Comment by MuhammadShahryiar** [comment]
I am getting this error : 
FieldError at /
Unsupported lookup 'exact' for EncryptedCharField or join on the field not permitted, perhaps you meant exact or iexact?

Can someone please help me solve this? 

Thank you.

**Comment by thismatters** [comment]
@MuhammadShahryiar Please see https://github.com/georgemarshall/django-cryptography/issues/10 

> Given the nature of data encryption, anything other than `isnull` is not query-able. This is a side affect of encrypting the data in the first place, as the output will change even when the input does not.

**Comment by aymaneMx** [comment]
@ademidun any update here on how you solved this issue, please?

**Comment by redblacktree** [comment]
My issue turned out to be that I had added encrypt() to an existing field, and I didn't follow the instructions here: https://django-cryptography.readthedocs.io/en/latest/migrating.html
