### ISSUE TITLE
Error accessing the encrypt fields.

### ISSUE THREAD

**Issue by kamaleshtangudu** [georgemarshall/django-cryptography#53]
Data got encrypted when I wrapped my created a field that is wrapped with encrypt method. But when I access the obj.field Value Error is raised. 
`ValueError: Invalid padding bytes`

Which in turn raises
`django_cryptography.utils.crypto.InvalidToken`

Django==3.0.7
djangorestframework==3.11.0
cryptography==3.1
django-cryptography==1.0

**Comment by kamaleshtangudu** [comment]
I think the issue might be because of the secret key I am using. It would be very helpful if someone can help me with creating a proper CRYPTOGRAPHY_KEY for this.

**Comment by thismatters** [comment]
Existing data _is not_ encrypted automatically when you wrap an existing field (with existing data) with the `encrypt` method.

Did you do your own migration to get any existing plaintext data into the encrypted field?

**Comment by kamaleshtangudu** [comment]
Yes, I wrote the migration. The data is encrypted inside the DB.

**Comment by kamaleshtangudu** [comment]
@thismatters anything you can help with here?

**Comment by thismatters** [comment]
Could there have been an issue with your token? Are you certain that you're using the same token (and salt) as that you used when doing the encrypting migration?

**Comment by kamaleshtangudu** [comment]
No, I have generated a token with `os.urandom(32)` and added it as CRYPTOGRAPHY_KEY in django settings. Did not make any changes to it.

**Comment by thismatters** [comment]
To be sure, you have generated a string literal and set that as `CRYPTOGRAPHY_KEY`, you're not setting `CRYPTOGRAPHY_KEY = os.urandom(32)`, right?

**Comment by kamaleshtangudu** [comment]
Yup I have generated a value from my python shell and was using it.

**Comment by kamaleshtangudu** [comment]
Values in my settings look like this,
`
from cryptography.hazmat.backends.openssl.backend import backend
CRYPTOGRAPHY_BACKEND = backend
CRYPTOGRAPHY_KEY=b'v\xce\x0e\xe2\xbc\xdb&\x05q\xfb\xa9\xff\x95\xb2\x9d9Cc\x81\xf9\xb0_\x8a\xbeG\xaf\x05\xf0oDt\xa8'
`

The data migration looks like this, this is third migration. The first two migrations are auto generated for renaming the field and creating encrypt field. 
```
# Generated by Django 3.0.7 on 2021-04-22 15:16

from django.db import migrations


def forwards_encrypted_char(apps, schema_editor):
    User = apps.get_model("users", "User")

    for row in User.objects.all():
        row.last_name = row.old_last_name
        row.save(update_fields=["last_name"])


def reverse_encrypted_char(apps, schema_editor):
    User = apps.get_model("users", "User")

    for row in User.objects.all():
        row.old_last_name = row.last_name
        row.save(update_fields=["old_last_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_last_name'),
    ]

    operations = [
        migrations.RunPython(forwards_encrypted_char, reverse_encrypted_char),
    ]
```

**Comment by kamaleshtangudu** [comment]
My python version is 3.7.5 along with these pip packages.
Django==3.0.7
djangorestframework==3.11.0
cryptography==3.1
django-cryptography==1.0

**Comment by thismatters** [comment]
I would try again with a different key. I've only ever used an alphanumeric key.

You've confirmed that the migration works and that the data does appear encrypted in the database?

**Comment by kamaleshtangudu** [comment]
Alphanumeric keys did not work for me actually. Can you tell me how you have created an alphanumeric key that worked? I was
 always getting AES unsupported no. of bits error since it only supported 128, 192 and 256bits.

Yes and the data did encrypt, and example value for encrypted last_name looks like this, `\x113b2574b9bd2e278c06d076323256f4`

**Comment by kamaleshtangudu** [comment]
@thismatters could you find anything?

**Comment by thismatters** [comment]
I had misremembered the details about my key. It has punctuation as well, but no unicode characters or `\x##` sequences.

**Comment by thismatters** [comment]
I just noticed the bit about your backend:

```from cryptography.hazmat.backends.openssl.backend import backend 
CRYPTOGRAPHY_BACKEND = backend
```

I've only ever used the default backend. Is there some motivating factor for using the openssl backend?

**Comment by kamaleshtangudu** [comment]
This is something where I was confused. The docs said CRYPTOGRAPHY_BACKEND is not compulsory but whereas as the migrations were not working without this being provided.

**Comment by thismatters** [comment]
This is the extent of configuration I had to do:

```
CRYPTOGRAPHY_KEY = os.environ.get("CRYPTOGRAPHY_KEY", "nothing")
CRYPTOGRAPHY_SALT = os.environ.get("CRYPTOGRAPHY_SALT", "nothing")

INSTALLED_APPS = [
    ...
    "django_cryptography",
    ....
]
```

Try that while using an ascii only key (and salt)!

**Comment by kamaleshtangudu** [comment]
Okay let me try with them. However the backend I was using is the very backend that comes as a response from the default_backend function.

**Comment by kamaleshtangudu** [comment]
The docs does not seem to suggest that app needs to be added in the installed apps. Also going with these settings I am getting `AttributeError: 'Settings' object has no attribute 'CRYPTOGRAPHY_BACKEND'`

**Comment by thismatters** [comment]
Can you post the full traceback for this error `AttributeError: 'Settings' object has no attribute 'CRYPTOGRAPHY_BACKEND'`?

**Comment by thismatters** [comment]
when you got that last traceback had you put `django_cryptography` in the `INSTALLED_APPS`?

**Comment by thismatters** [comment]
I would like to see the text of that migration since that is where the exception is being raised.

**Comment by kamaleshtangudu** [comment]
Can you use this traceback, as the same error is getting returned even when I am retrying to generate the very 0012 migration. Initially when I was testing, I changed this setting after this creating this migration.
```Traceback (most recent call last):
  File "manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/home/i0501/Documents/work/patient-profile/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/i0501/Documents/work/patient-profile/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/i0501/Documents/work/patient-profile/venv/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/i0501/Documents/work/patient-profile/venv/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/i0501/Documents/work/patient-profile/venv/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/i0501/Documents/work/patient-profile/venv/lib/python3.7/site-packages/django/core/management/commands/makemigrations.py", line 142, in handle
    ProjectState.from_apps(apps),
  File "/home/i0501/Documents/work/patient-profile/venv/lib/python3.7/site-packages/django/db/migrations/state.py", line 221, in from_apps
    model_state = ModelState.from_model(model)
  File "/home/i0501/Documents/work/patient-profile/venv/lib/python3.7/site-packages/django/db/migrations/state.py", line 413, in from_model
    fields.append((name, field.clone()))
  File "/home/i0501/Documents/work/patient-profile/venv/lib/python3.7/site-packages/django_cryptography/fields.py", line 135, in clone
    self.base_class(*args, **kwargs), self.key, self.ttl)
  File "/home/i0501/Documents/work/patient-profile/venv/lib/python3.7/site-packages/django_cryptography/fields.py", line 218, in encrypt
    return get_encrypted_field(type(base_field))(*args, **kwargs)
  File "/home/i0501/Documents/work/patient-profile/venv/lib/python3.7/site-packages/django_cryptography/fields.py", line 103, in __init__
    self._fernet = FernetBytes(self.key)
  File "/home/i0501/Documents/work/patient-profile/venv/lib/python3.7/site-packages/django_cryptography/utils/crypto.py", line 109, in __init__
    self._backend = settings.CRYPTOGRAPHY_BACKEND
  File "/home/i0501/Documents/work/patient-profile/venv/lib/python3.7/site-packages/appconf/base.py", line 126, in __getattr__
    return getattr(self._meta.holder, name)
  File "/home/i0501/Documents/work/patient-profile/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 77, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'CRYPTOGRAPHY_BACKEND'
```

**Comment by thismatters** [comment]
Before upgrading version, just as a sanity check can you open a django shell (within your project) and run the following three lines:

```
from django_cryptography.conf import CryptographyConf
settings = CryptographyConf()
settings.CRYPTOGRAPHY_BACKEND
```

And see if the `AttributeError` is raised.

**Comment by kamaleshtangudu** [comment]
Upgrading to django-3.2.x and running this on the shell still causes and issue. I think I might have got the issue partially, I use django-configurations to achieve class based settings rather than the classic django settings(file based settings). AppConf class might be something that is only compatible with classic settings and not with django-configurations.

**Comment by thismatters** [comment]
I don't see how that could be possible. 

I've just re-created your environment in a docker container and the commands executed as expected:
```
/test # python manage.py shell
Python 3.7.10 (default, Apr 15 2021, 05:25:07) 
[GCC 10.2.1 20201203] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from django_cryptography.conf import CryptographyConf
>>> settings = CryptographyConf()
>>> settings.CRYPTOGRAPHY_BACKEND
<cryptography.hazmat.backends.openssl.backend.Backend object at 0x7fd6cb3d4750>
>>> 
now exiting InteractiveConsole...
/test # pip freeze | grep cryptography
cryptography==3.1
django-cryptography==1.0
/test # pip freeze | grep Django
Django==3.0.7
```

Have you altered any files the `django_cryptography` package?

**Comment by thismatters** [comment]
I realized that I was using a newer version of python (3.7.10) while you're using 3.7.5.

I was unable to get my test to run in 3.7.5. I recommend upgrading your python. At a minimum I would say you should be using the most recent minor version (3.7.10), but you should consider getting to the most recent major version as well.

**Comment by thismatters** [comment]
Oh, I hadn't seen that you were using `django-configurations`.
