### ISSUE TITLE
Encrypted field not working in Django 4.0 - ugettext_lazy deprecated

### ISSUE THREAD

**Issue by rafathossain** [georgemarshall/django-cryptography#69]
```
Traceback (most recent call last):
  File "/Users/rafathossain/PycharmProjects/DashMetro_MetroVPS/manage.py", line 22, in <module>
    main()
  File "/Users/rafathossain/PycharmProjects/DashMetro_MetroVPS/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/rafathossain/PycharmProjects/DashMetro_MetroVPS/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/Users/rafathossain/PycharmProjects/DashMetro_MetroVPS/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/Users/rafathossain/PycharmProjects/DashMetro_MetroVPS/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/rafathossain/PycharmProjects/DashMetro_MetroVPS/venv/lib/python3.9/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/Users/rafathossain/PycharmProjects/DashMetro_MetroVPS/venv/lib/python3.9/site-packages/django/apps/config.py", line 304, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rafathossain/PycharmProjects/DashMetro_MetroVPS/metro_admin/models.py", line 3, in <module>
    from django_cryptography.fields import encrypt
  File "/Users/rafathossain/PycharmProjects/DashMetro_MetroVPS/venv/lib/python3.9/site-packages/django_cryptography/fields.py", line 7, in <module>
    from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/Users/rafathossain/PycharmProjects/DashMetro_MetroVPS/venv/lib/python3.9/site-packages/django/utils/translation/__init__.py)
```

I think this one is deprecated and replaced

**from django.utils.translation import ugettext_lazy as _** >> **from django.utils.translation import gettext_lazy as _**

Please make an update of the package to fix this.

**Comment by georgemarshall** [comment]
Fixed in #68
